In [ ]:
import tensorflow as tf
import pandas as pd

In [ ]:
# 데이터를 준비하고
(독립, 종속), _ = tf.keras.datasets.mnist.load_data()
print(독립.shape, 종속.shape)

독립 = 독립.reshape(60000, 28, 28, 1) # convolution layer는 이미지 하나의 shape모양이 3차원 모양이어야한다.
종속 = pd.get_dummies(종속) # 범주형 데이터는 원핫인코딩을 해줘야 한다.
print(독립.shape, 종속.shape)

Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11493376/11490434 [==============================] - 0s 0us/step
(60000, 28, 28) (60000,)
(60000, 28, 28, 1) (60000, 10)

In [ ]:
# 모델을 만들고
X = tf.keras.layers.Input(shape=[28, 28, 1])
H = tf.keras.layers.Conv2D(3, kernel_size=5, activation='swish')(X)
H = tf.keras.layers.Conv2D(6, kernel_size=5, activation='swish')(H)
H = tf.keras.layers.Flatten()(H)
H = tf.keras.layers.Dense(84, activation='swish')(H)
Y = tf.keras.layers.Dense(10, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [ ]:
# 모델을 학습하고
model.fit(독립, 종속, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 14s 4ms/step - loss: 1.6715 - accuracy: 0.8783
Epoch 2/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0759 - accuracy: 0.9786
Epoch 3/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0411 - accuracy: 0.9882
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0256 - accuracy: 0.9916
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0210 - accuracy: 0.9937
Epoch 6/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0165 - accuracy: 0.9946
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0163 - accuracy: 0.9951
Epoch 8/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0120 - accuracy: 0.9962
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0123 - accuracy: 0.9968
Epoch 10/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0143 - accuracy: 0.9961

In [ ]:
# 모델을 이용합니다.
pred = model.predict(독립[0:5])
pd.DataFrame(pred).round(2)

     0    1    2    3    4    5    6    7    8    9
0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
1  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
3  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [ ]:
종속[0:5]

   0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  1  0  0  0  0
1  1  0  0  0  0  0  0  0  0  0
2  0  0  0  0  1  0  0  0  0  0
3  0  1  0  0  0  0  0  0  0  0
4  0  0  0  0  0  0  0  0  0  1

In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         [(None, 28, 28, 1)]       0
_________________________________________________________________
conv2d (Conv2D)              (None, 24, 24, 3)         78
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 20, 20, 6)         456
_________________________________________________________________
flatten (Flatten)            (None, 2400)              0
_________________________________________________________________
dense (Dense)                (None, 84)                201684
_________________________________________________________________
dense_1 (Dense)              (None, 10)                850
=================================================================
Total params: 203,068
Trainable params: 203,068
Non-trainable params: 0
_________________________________________________________________